### ISSUE TITLE
Issue in formula passed in model.matrix

### ISSUE THREAD

**Issue by kshitizkhatri** [paragkale/kaggle-airbnb#1]
Hi!

I am a beginner to R as well as Kaggle. I was going through your code, I couldn't figure out the meaning of the following syntax:

all_usrs <- cbind(all_usrs[,c(1,2), drop=FALSE], model.matrix(~ -1 + ., all_usrs[,-c(1,2)]))

Can you please explain the meaning of the formula used in the model.matrix function.

I want to try something similar with less number of variables.

Thanks!

**Comment by paragkale** [comment]
> > > all_usrs[,c(1,2), drop=FALSE]
> > > This is where I select first two columns of all_usrs to bind with the 
> > > other part. drop = FALSE is not really required in this case since there 
> > > are 2 columns in the data.frame
> > > 
> > > model.matrix(~ -1 + ., all_usrs[,-c(1,2)])
> > > Here I expand the all_usr data frame (except the first 2 columns). This 
> > > will one-hot encode all factor variables. For example if you have a 
> > > variable V with values a, b, c - it will look like this

V
a
b
c
b

will become
Va Vb Vc
1    0   0
0    1   0
0    0   1
0    1   0
This is one of the ways you can convert categorical variable into numbers.

Regards,
Parag

**Comment by kshitizkhatri** [comment]
Thanks for the reply parag!

I also wanted to know what does this line represent: ~ -1 + . 

I checked the documentation for the model.matrix and some of the examples, I want to know what is the difference between ~ . -1 and the one above. Why the plus sign?

TIA.

**Comment by paragkale** [comment]
Both are exactly same. Checkout the documentation for formula. Sometimes 
there are multiple ways in which you can represent the same formula.
